version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.owasp:dependency-check-maven
    versions:
    - 6.0.5
    - 6.1.0
    - 6.1.1
    - 6.1.2
    - 6.1.3
  - dependency-name: com.google.cloud:google-cloud-logging
    versions:
    - 2.1.3
    - 2.1.5
    - 2.2.0
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.7.7
    - 3.8.0
  - dependency-name: com.fasterxml.jackson.core:jackson-databind
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.core:jackson-core
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: org.json:json
    versions:
    - "20201115"
